### ISSUE TITLE
very minor suggestion

### ISSUE THREAD

**Issue by Nick-Mul** [m3g/PDBTools.jl#17]
Very minor suggestion but it seems tricky to add hydrogens with any Julia package. A work around is obviously to use obabel but I was wondering if you could envisage some functionality here? For example https://github.com/jensengroup/propka/tree/master/propka hydrogens.py ?

**Comment by lmiq** [comment]
I don't think implementing that from scratch is worth the trouble. But maybe a simple interface to Obabel is easy. Can you give me an example on how to do it with that?

**Comment by lmiq** [comment]
In any case, I have added a `add_hydrogens!` function that calls `obabel` externally, to add hydrogens to a PDB file (in version 1.3.0):

https://m3g.github.io/PDBTools.jl/dev/tools/

**Comment by Nick-Mul** [comment]
Oh great :)
